# This script is to test the functionality of DateTime.py

import subprocess

print("DateTime.py Functionality Test!")
print()
print("+++++++++++++++++++++++++++++++++++++++++++++++")
print()
print("Test Daylight savings time spring forward :")
print("python3 DateTime.py 03:12:2022:21:30:CDT UTC")
print()
subprocess.call("python3 DateTime.py 03:12:2022:21:30:CDT UTC", shell=True)
print()
print("Compare to :")
print()
print("03 13 2022")
print("03 : 30 : UTC")
print()
print("+++++++++++++++++++++++++++++++++++++++++++++++")
print()
print("Test Daylight savings time fall back :")
print("python3 DateTime.py 11:05:2022:21:30:CDT UTC")
print()
subprocess.call("python3 DateTime.py 11:05:2022:21:30:CDT UTC", shell=True)
print()
print("Compare to :")
print()
print("11 06 2022")
print("01 : 30 : UTC")
print()
print("+++++++++++++++++++++++++++++++++++++++++++++++")
print()
print("Test month and year change :")
print("python3 DateTime.py 12:31:2022:19:30:CDT UTC")
print()
subprocess.call("python3 DateTime.py 12:31:2022:19:30:CDT UTC", shell=True)
print()
print("Compare to :")
print()
print("01 01 2023")
print("00 : 30 : UTC")
print()
print("+++++++++++++++++++++++++++++++++++++++++++++++")